<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.0.11 INSTALLER - Sunday 20th of May 2012 02:18:23 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | https://github.com/hybridauth/hybridauth
*  (c) 2009-2011 HybridAuth authors | hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://likeguide.com/hybridauth", 

		"providers" => array ( 
			// openid providers
			
			
			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "9hvj1btmfvhk", "secret" => "w1ONNdmLEcsZk1mF") 
			),
			"Facebook" => array ( 
        "enabled" => true,
        "keys"    => array ( "id" => "242828585838365", "secret" => "b561622c4d204f08b84e73c68e284eed" ),
// A comma-separated list of permissions you want to request from the user. See the Facebook docs for a full list of available permissions: http://developers.facebook.com/docs/reference/api/permissions.
         "scope"   => "email,read_friendlists", 
// The display context to show the authentication page. Options are: page, popup, iframe, touch and wap. Read the Facebook docs for more details: http://developers.facebook.com/docs/reference/dialogs#display. Default: page
                                "display" => "popup" 
                        ),
		
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => "",
	);